### ISSUE TITLE
Webpack production build issue - UglifyJS can't minify ES6 

### ISSUE THREAD

**Issue by jonathanchrisp** [pgilad/react-page-visibility#1]
## Overview 

When using this package within our project, when building for production using webpack we get an UglifyJS error, it appears it's trying to minify ES6 code which it doesn't support. 

```
ERROR in 0.js from UglifyJs
Unexpected token: punc (() [./~/react-page-visibility/index.js:10,0][0.js:25213,22]
```

We did look at upgrading to uglify-es but unfortunately, the webpack uglify-js plugin doesn't currently support the new API.

I'll raise a PR against this issue which will create a new webpack build which will allow us to use this package within our project. Just to note I've noticed a few additional updates which can be done so I'll bundle these in also. If you're not happy in the review we can switch things out etc.

**Comment by pgilad** [comment]
Closed by https://github.com/pgilad/react-page-visibility/commit/a922b84589b0af258158069bc1680c81a3bfa141

Thanks!
