### ISSUE TITLE
Broken import in 4.2.0

### ISSUE THREAD

**Issue by bstst** [pgilad/react-page-visibility#12]
The 4.2.0 release seems to be broken:

`ERROR in ./node_modules/react-page-visibility/dist/index.es5.js
Module not found: Error: Can't resolve './PageVisibility' in '/Users/martin/Projects/****/node_modules/react-page-visibility/dist'`

**Comment by pgilad** [comment]
Yeah that was a bad release, please use version 5+. Very sorry about that.. :black_circle: 
I need to deprecate it

**Comment by bstst** [comment]
Indeed, `5.0.0` works, thanks.
