### ISSUE TITLE
TypeError from usePageVisibility hook when visibility API isn't supported

### ISSUE THREAD

**Issue by markdascher** [pgilad/react-page-visibility#14]
This line blows up when visibility API isn't supported (e.g. server-side rendering):

https://github.com/pgilad/react-page-visibility/blob/394a46a63cdce218cc76eb8200a250f724fcf1e8/src/usePageVisibility.js#L8

getHandlerArgs tries to extract properties from visibility, which is null:

```
TypeError: Cannot read property 'hidden' of null
```

Should this be protected by an `isSupportedLocal` conditional? Or should getHandlerArgs short-circuit when visibility is null?

**Comment by pgilad** [comment]
React hooks support was recently added and I'm not an expert on it.. Will gladly support either solution you find best

**Comment by pgilad** [comment]
@markdascher this [commit](https://github.com/pgilad/react-page-visibility/commit/a58ad3a487d3a53614ff1c512de635330a89c19b) should take care of it
