### ISSUE TITLE
Components Showing as Visible on load?

### ISSUE THREAD

**Issue by wootwoot1234** [pgilad/react-page-visibility#17]
I want to know if components from a list of components are on the screen on load so that I can tell it get additional data from the DB but not get the additional data of the other components until they are visible (user scrolls down).

I have a page that on load queries the DB for new items.  When it returns it populates the screen with a list of components:

    {items.map(item => {
        return (
            <CustomComponent key={`MCL${item._id}`} />
        );
    })}

So on load items is equal to [] and then after it gets the items prints the `<CustomComponent />` to screen.  There are over 50 items and it only takes 10 `<CustomComponent />`'s to fill the screen so about 40 of them should not be visible.

In the customer component I have:

    import {usePageVisibility} from "react-page-visibility";

    function CustomComponent(props) {
        const isVisible = usePageVisibility();
        console.log("isVisible 0", isVisible);
        useEffect(() => {
            console.log("isVisible 1", isVisible);
        }, [isVisible]);
    }

On load, I see in the console `isVisible 0 true` and `isVisible 1 true` 50 times but never see it print isVisible as false unless change tabs os something similar.  I would expect it to print `isVisible 0 true` about 10 times and then `isVisible 0 false` about 40 times.

**Comment by pgilad** [comment]
Browser page visibility only activates when the active tab is visible by the user, it's basically a boolean state.
So it's useful if the user switches tabs or minimizes the browser and then restores it. Even if the entire viewport is hidden behind another window and then suddenly visible.

That said, it's not meant for screen partial viewports like scrolling, it's simply an unrelated API, and this component can't support it.
