### ISSUE TITLE
Error with npm - Could not resolve dependency

### ISSUE THREAD

**Issue by chrishrtmn** [pgilad/react-page-visibility#20]
I updated my package dependencies and am running into this error when I try to install react-page-visibility (6.3.0):

![Screen Shot 2021-01-15 at 4 15 18 PM](https://user-images.githubusercontent.com/226349/104779311-e8374780-574c-11eb-85e5-f5b4020f0a2b.png)

Any plans to fix this or should I run the command to force an incorrect/possibly broken resolution?

Thanks!

**Comment by pgilad** [comment]
Thanks for reporting, should be fixed here: https://github.com/pgilad/react-page-visibility/commit/16039f91cdaa6432179a0e824755d057e67ad42f

Try version `6.4.0` 😄
