### ISSUE TITLE
Not very useful - Visibility API vs blur/focus

### ISSUE THREAD

**Issue by 1aerostorm** [pgilad/react-page-visibility#21]
Implementation of this library is quite good, but the Visibility API is not very useful at all.
It says what page is visible when it is actually hidden by and overlaying window.

E.g. if you are using it in a messenger, and messenger shows title/favicon notification if page is not visible, it will confuse the user: if user minimizes the browser or changed the tab, it works, but if he activates another application window, it doesn't. This behaviour will look like a bug.

This library can be used for some special cases, even in React, but not for wide usage.

**Comment by pgilad** [comment]
Feel free to suggest an alternative API to use, this is a react interface for document.visibility in general

**Comment by 1aerostorm** [comment]
@pgilad as mentioned in title of the issue, it is better to use blur\focus API. (And document.visibility is the "Visibility API").

**Comment by pgilad** [comment]
What do you say about https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API ?

```
Developers have historically used imperfect proxies to detect this. For example, watching for blur and focus events on the window helps you know when your page is not the active page, but it does not tell you that your page is actually hidden to the user. The Page Visibility API addresses this.

Note: While onblur and onfocus will tell you if the user switches windows, it doesn't necessarily mean it's hidden. Pages only become hidden when the user switches tabs or minimizes the browser window containing the tab.
```

**Comment by 1aerostorm** [comment]
@pgilad "Visibility API" = Page Visibility API = API which used in your library.
