### ISSUE TITLE
npm warning when using React 16

### ISSUE THREAD

**Issue by fmichea** [pgilad/react-page-visibility#4]
Hey, I may be mistaken cause I am new to React, but it seems that this package is pinned on React 15, which creates the following warning when using npm with React 16:

```
npm WARN react-page-visibility@1.0.0 requires a peer of react@^15.5.4 but none is installed. You must install peer dependencies yourself.
```

Now I just tried it with 16 anyway and it seems that at least for my usecase, this still works great. Would it be possible to unpin or at least add React 16 to possible dependencies?

Cheers

**Comment by pgilad** [comment]
If the package can support both 15 and 16 I'd be happy to extend the peer requirements

**Comment by pgilad** [comment]
Fixed in https://github.com/pgilad/react-page-visibility/commit/cec97ac4daa484c73e7a4b28927605c47af2170e

Thanks for reporting!

**Comment by fmichea** [comment]
Cheers
