### ISSUE TITLE
New version of Chrome no longer fires 'visibilitychange' coming from background tabs

### ISSUE THREAD

**Issue by rj-david** [pgilad/react-page-visibility#9]
Starting Chrome 77 in Android (to follow in other platforms), background tabs are being "frozen" after 5 minutes of inactivity. When that tab becomes active, the event `visibilitychange` is no longer being fired. Instead, the new event `resume` is being used.

More details here: https://developers.google.com/web/updates/2018/07/page-lifecycle-api

**Comment by pgilad** [comment]
Oh, good to know, thanks for the heads-up... I wonder what it'll take to support this for both legacy & new versions of Chrome, and how will it work with cross-browser support.

If you have time I'll really appreciate a PR for this

**Comment by rj-david** [comment]
Will try to submit a PR once we are done with the tests this coming week

**Comment by pgilad** [comment]
Hey @rj-david any updates? Chrome 77 was already released, no need to rush though 😏

**Comment by pgilad** [comment]
@rj-david looking again at the lifecycle chart, it seems that first a document is in `hidden` state, then gets to `frozen`, then `resumed` (so back to `hidden` again) and then there is a visibility change event which will make the page `passive` or `active`. Either way the visibility change event must be fired and so even though we have partial support (i.e no lifecycle events for resume/frozen and distinction between passive/active) this will still allow users to react to primary hidden/visible state.
![image](https://user-images.githubusercontent.com/4533329/103204166-5ed7e680-48ff-11eb-8312-8c60764bac9a.png)

**Comment by rj-david** [comment]
@pgilad too bad that this was closed. The new API can go from Frozen to Active and firing only the Resume event.

That is also clear on the same graph above. From resume, it can proceed to pageshow event and the result can be either hidden, passive or ACTIVE without firing visibilitychange.

A lot of apps using this package is not being considered as visible once the tab comes from frozen to active
